config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static#home'

  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  resources :gossips
  resources :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags
  has_many :comments
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    def index
    @gossip = Gossip.all
    puts "ssssssss"
    end

    def show
    @gossip = Gossip.find(params[:id])
    puts @gossip
    puts "sssssssss"
    end
    def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end

    def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    end

    def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end

    def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end

    def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
    @gossip = Gossip.all

    end

    def show
    @gossip = Gossip.find(params[:id])
    @comment = @gossip.comments
    
   
    end
    def new
    @gossip = Gossip.new
      
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end

    def create
        @gossip = Gossip.create(title: params[:gossip][:title],content: params[:gossip][:content], user_id:5)
        
        redirect_to gossips_path
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    end

    def edit
    @gossip = Gossip.find(params[:id])    
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end

    def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(title: params[:gossip][:title],content: params[:gossip][:content], user_id:5)
    redirect_to gossips_path(params[:id])

    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end

    def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path(params[:id])

    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
end

app/views/gossips/edit.html.erb
<%= form_for @gossip do |form|%>

    <div class="form-group">
        <label>Edite ton titre</label>
        <%= form.text_field :title, class: 'form-control'%>
    </div>

    <div class="form-group">
        <label>Edite ta Description</label>
        <%= form.text_field :title, class: 'form-control'%>
    </div>

<div class="form-group">
    <button type="submit">Créer</button>
</div>


<%end%>

app/views/gossips/index.html.erb
<div class="container-fluid my-5">
	<h3>Incroyable, on retrouve tous les potins ici !</h3>
	<button><%= link_to "créer un nouveau gossip", new_gossip_path %></button>
</div>



<% @gossip.each do |gossip | %>
<div class="card align-self-center my-2" style="width: 100rem;">
  <div class="card-body">
    <h5 class="card-title"><%= link_to "#{gossip.title}", "/gossips/#{gossip.id}" %>   </h5>
    <p class="card-text"><%= gossip.content %></p>
	<ul> <%= gossip.created_at %> </ul>

</div>
</div>

<% end %>

app/views/gossips/new.html.erb
<%= form_for @gossip do |form|%>

    <div class="form-group">
        <label>Titre</label>
        <%= form.text_field :title, class: 'form-control'%>
    </div>

    <div class="form-group">
        <label>Description</label>
        <%= form.text_field :title, class: 'form-control'%>
    </div>

<div class="form-group">
    <button type="submit">Créer</button>
</div>


<%end%>

app/views/gossips/show.html.erb
<div class="container-fluid my-5">
	<h3><%= @gossip.title %></h3>
<button><%= link_to "Edite ton sacrament de potin", edit_gossip_path %></button>
<%= link_to "Supprimer le Gossip", gossip_path, method: :delete, class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

<div class="card align-self-center mt-2" style="width: 100rem;">
    <div class="card-body">
    <h5 class="card-title"><%= link_to "#{@gossip.user.first_name}", "/user/#{@gossip.user.id}" %></h5>
    <p class="card-text"><%= @gossip.content %></p>
</div>
<br>
<br>
<% @comment.each do |comment| %>
<div class="card align-self-center my-2" style="width: 100rem;">
  <div class="card-body">
    <h5 class="card-title"><%= link_to "#{comment.content}", "/gossips/#{@gossip.id}" %> </h5>    
	<ul> <%= comment.created_at %> </ul>

</div>
</div>

<% end %>